const CACHE_NAME = 'yumbuni-ecd-v2';
const ASSETS = [
  './index.html',
  './manifest.json',
  './icon-192.png',
  './icon-512.png',
  './font-fredoka.ttf',
  './font-baloo2.ttf',
  './audio-letter_a.mp3',
  './audio-letter_b.mp3',
  './audio-letter_c.mp3',
  './audio-letter_d.mp3',
  './audio-letter_e.mp3',
  './audio-letter_f.mp3',
  './audio-letter_g.mp3',
  './audio-letter_h.mp3',
  './audio-letter_i.mp3',
  './audio-letter_j.mp3',
  './audio-letter_k.mp3',
  './audio-letter_l.mp3',
  './audio-letter_m.mp3',
  './audio-letter_n.mp3',
  './audio-letter_o.mp3',
  './audio-letter_p.mp3',
  './audio-letter_q.mp3',
  './audio-letter_r.mp3',
  './audio-letter_s.mp3',
  './audio-letter_t.mp3',
  './audio-letter_u.mp3',
  './audio-letter_v.mp3',
  './audio-letter_w.mp3',
  './audio-letter_x.mp3',
  './audio-letter_y.mp3',
  './audio-letter_z.mp3',
  './audio-num_0.mp3',
  './audio-num_1.mp3',
  './audio-num_10.mp3',
  './audio-num_100.mp3',
  './audio-num_101.mp3',
  './audio-num_102.mp3',
  './audio-num_103.mp3',
  './audio-num_104.mp3',
  './audio-num_105.mp3',
  './audio-num_106.mp3',
  './audio-num_107.mp3',
  './audio-num_108.mp3',
  './audio-num_109.mp3',
  './audio-num_11.mp3',
  './audio-num_110.mp3',
  './audio-num_12.mp3',
  './audio-num_13.mp3',
  './audio-num_14.mp3',
  './audio-num_15.mp3',
  './audio-num_16.mp3',
  './audio-num_17.mp3',
  './audio-num_18.mp3',
  './audio-num_19.mp3',
  './audio-num_2.mp3',
  './audio-num_20.mp3',
  './audio-num_21.mp3',
  './audio-num_22.mp3',
  './audio-num_23.mp3',
  './audio-num_24.mp3',
  './audio-num_25.mp3',
  './audio-num_26.mp3',
  './audio-num_27.mp3',
  './audio-num_28.mp3',
  './audio-num_29.mp3',
  './audio-num_3.mp3',
  './audio-num_30.mp3',
  './audio-num_31.mp3',
  './audio-num_32.mp3',
  './audio-num_33.mp3',
  './audio-num_34.mp3',
  './audio-num_35.mp3',
  './audio-num_36.mp3',
  './audio-num_37.mp3',
  './audio-num_38.mp3',
  './audio-num_39.mp3',
  './audio-num_4.mp3',
  './audio-num_40.mp3',
  './audio-num_41.mp3',
  './audio-num_42.mp3',
  './audio-num_43.mp3',
  './audio-num_44.mp3',
  './audio-num_45.mp3',
  './audio-num_46.mp3',
  './audio-num_47.mp3',
  './audio-num_48.mp3',
  './audio-num_49.mp3',
  './audio-num_5.mp3',
  './audio-num_50.mp3',
  './audio-num_51.mp3',
  './audio-num_52.mp3',
  './audio-num_53.mp3',
  './audio-num_54.mp3',
  './audio-num_55.mp3',
  './audio-num_56.mp3',
  './audio-num_57.mp3',
  './audio-num_58.mp3',
  './audio-num_59.mp3',
  './audio-num_6.mp3',
  './audio-num_60.mp3',
  './audio-num_61.mp3',
  './audio-num_62.mp3',
  './audio-num_63.mp3',
  './audio-num_64.mp3',
  './audio-num_65.mp3',
  './audio-num_66.mp3',
  './audio-num_67.mp3',
  './audio-num_68.mp3',
  './audio-num_69.mp3',
  './audio-num_7.mp3',
  './audio-num_70.mp3',
  './audio-num_71.mp3',
  './audio-num_72.mp3',
  './audio-num_73.mp3',
  './audio-num_74.mp3',
  './audio-num_75.mp3',
  './audio-num_76.mp3',
  './audio-num_77.mp3',
  './audio-num_78.mp3',
  './audio-num_79.mp3',
  './audio-num_8.mp3',
  './audio-num_80.mp3',
  './audio-num_81.mp3',
  './audio-num_82.mp3',
  './audio-num_83.mp3',
  './audio-num_84.mp3',
  './audio-num_85.mp3',
  './audio-num_86.mp3',
  './audio-num_87.mp3',
  './audio-num_88.mp3',
  './audio-num_89.mp3',
  './audio-num_9.mp3',
  './audio-num_90.mp3',
  './audio-num_91.mp3',
  './audio-num_92.mp3',
  './audio-num_93.mp3',
  './audio-num_94.mp3',
  './audio-num_95.mp3',
  './audio-num_96.mp3',
  './audio-num_97.mp3',
  './audio-num_98.mp3',
  './audio-num_99.mp3',
  './audio-op_minus.mp3',
  './audio-op_plus.mp3',
  './audio-op_times.mp3',
  './audio-phrase_find_letter.mp3',
  './audio-phrase_find_number.mp3',
  './audio-phrase_find_shape.mp3',
  './audio-phrase_great_job.mp3',
  './audio-phrase_nice_try.mp3',
  './audio-shape_circle.mp3',
  './audio-shape_diamond.mp3',
  './audio-shape_heart.mp3',
  './audio-shape_square.mp3',
  './audio-shape_star.mp3',
  './audio-shape_triangle.mp3',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS))
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        if (response && response.status === 200) {
          const clone = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
        }
        return response;
      }).catch(() => cached);
    })
  );
});
